#mybatis.type-aliases-package=com.neo.model

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soccer?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: admin234
    driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    #默认前缀
    contextPath: /
    # 指定环境
    profiles:
      active: local

  # jsp配置
  mvc:
    view:
      prefix: /templates/
      suffix: .jsp
      static-path-pattern: /resources/static/**
  # Redis数据库索引（默认为0）
  redis:
    database: 0
  # Redis服务器地址
    host: localhost
  # Redis服务器连接端口
    port: 6379
  # Redis服务器连接密码（默认为空）
    password:
  # 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce:
      pool:
        max-active: 8
  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
  # 连接池中的最大空闲连接 默认 8
        max-idle: 8
  # 连接池中的最小空闲连接 默认 0
        min-idle: 0

jdbc:
  initLocation: classpath:source/initDB.sql
  dataLocation: classpath:source/populateDB.sql




#
##log配置文件
#logging:
#  config: classpath:logback-cms.xml
#  #log路径
#  path: ~/logs/
